on: push
jobs :
    build-node:
     runs-on: ubuntu-latest
     container: node:14
     steps:
         -run: node --version
         -run: npm --version
     steps:
         -uses: actions/checkout@v3
     steps:    
         -run: npm install
         -run: node index.js
